import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout"; // Import the client-side layout
import Head from "next/head"; // Import Next.js Head component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Correct way to add metadata in Next.js 13+
export const metadata = {
  title: "Lumina Store",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", // Path to your favicon (inside `public/` folder)
  },
  manifest: "/manifest.json", // Reference to your manifest file
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head> 
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href={metadata.icons.icon} />
        <link rel="manifest" href={metadata.manifest} />
        <meta name="theme-color" content="#000000" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
