import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout"; // Client component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Correct metadata setup
export const metadata = {
  title: "Lumina Store",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", // Ensure this file exists in `public/`
  },
  manifest: "/manifest.json",
  themeColor: "#000000",
};

// ✅ Fix: No <Head> needed in App Router
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
